[package]
name = "falling_sand"
version = "0.1.0"
authors = ["filip <filip270798@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.120.0"